spring.application.name=user-service

server.servlet.context-path=/api/v1.0


spring.datasource.url=jdbc:postgresql://localhost:5432/salon_db
spring.datasource.username=postgres
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.format_sql=true


spring.jpa.defer-datasource-initialization=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


spring.sql.init.mode=always
spring.sql.init.platform=postgres

spring.sql.init.data-locations=classpath:insert_tb_users.sql
